# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main_window.ui'
##
## Created by: Qt User Interface Compiler version 6.2.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QLabel, QPushButton,
    QSizePolicy, QWidget)

class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(530, 495)
        Form.setMinimumSize(QSize(530, 495))
        Form.setMaximumSize(QSize(530, 495))
        font = QFont()
        Form.setFont(font)
        Form.setStyleSheet(u"")
        self.label = QLabel(Form)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 20, 250, 20))
        font1 = QFont()
        font1.setPointSize(18)
        self.label.setFont(font1)
        self.label.setScaledContents(True)
        self.label.setAlignment(Qt.AlignCenter)
        self.btn_airplane_add = QPushButton(Form)
        self.btn_airplane_add.setObjectName(u"btn_airplane_add")
        self.btn_airplane_add.setGeometry(QRect(10, 48, 250, 41))
        font2 = QFont()
        font2.setPointSize(14)
        self.btn_airplane_add.setFont(font2)
        self.btn_airplane_add.setAutoExclusive(False)
        self.btn_airplane_add.setFlat(False)
        self.btn_airplane_change = QPushButton(Form)
        self.btn_airplane_change.setObjectName(u"btn_airplane_change")
        self.btn_airplane_change.setGeometry(QRect(10, 83, 250, 41))
        self.btn_airplane_change.setFont(font2)
        self.btn_airplane_change.setAutoExclusive(False)
        self.btn_airplane_change.setFlat(False)
        self.btn_airplane_del = QPushButton(Form)
        self.btn_airplane_del.setObjectName(u"btn_airplane_del")
        self.btn_airplane_del.setGeometry(QRect(10, 118, 250, 41))
        self.btn_airplane_del.setFont(font2)
        self.btn_airplane_del.setAutoExclusive(False)
        self.btn_airplane_del.setFlat(False)
        self.label_2 = QLabel(Form)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 190, 250, 20))
        self.label_2.setFont(font1)
        self.label_2.setScaledContents(True)
        self.label_2.setAlignment(Qt.AlignCenter)
        self.btn_cargo_add = QPushButton(Form)
        self.btn_cargo_add.setObjectName(u"btn_cargo_add")
        self.btn_cargo_add.setGeometry(QRect(10, 220, 250, 41))
        self.btn_cargo_add.setFont(font2)
        self.btn_cargo_add.setAutoExclusive(False)
        self.btn_cargo_add.setFlat(False)
        self.btn_cargo_del = QPushButton(Form)
        self.btn_cargo_del.setObjectName(u"btn_cargo_del")
        self.btn_cargo_del.setGeometry(QRect(10, 290, 250, 41))
        self.btn_cargo_del.setFont(font2)
        self.btn_cargo_del.setAutoExclusive(False)
        self.btn_cargo_del.setFlat(False)
        self.btn_cargo_change = QPushButton(Form)
        self.btn_cargo_change.setObjectName(u"btn_cargo_change")
        self.btn_cargo_change.setGeometry(QRect(10, 255, 250, 41))
        self.btn_cargo_change.setFont(font2)
        self.btn_cargo_change.setAutoExclusive(False)
        self.btn_cargo_change.setFlat(False)
        self.btn_custom_del = QPushButton(Form)
        self.btn_custom_del.setObjectName(u"btn_custom_del")
        self.btn_custom_del.setGeometry(QRect(270, 118, 250, 41))
        self.btn_custom_del.setFont(font2)
        self.btn_custom_del.setAutoExclusive(False)
        self.btn_custom_del.setFlat(False)
        self.label_3 = QLabel(Form)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(270, 21, 250, 20))
        self.label_3.setFont(font1)
        self.label_3.setScaledContents(True)
        self.label_3.setAlignment(Qt.AlignCenter)
        self.btn_custom_add = QPushButton(Form)
        self.btn_custom_add.setObjectName(u"btn_custom_add")
        self.btn_custom_add.setGeometry(QRect(270, 48, 250, 41))
        self.btn_custom_add.setFont(font2)
        self.btn_custom_add.setAutoExclusive(False)
        self.btn_custom_add.setFlat(False)
        self.btn_custom_change = QPushButton(Form)
        self.btn_custom_change.setObjectName(u"btn_custom_change")
        self.btn_custom_change.setGeometry(QRect(270, 83, 250, 41))
        self.btn_custom_change.setFont(font2)
        self.btn_custom_change.setAutoExclusive(False)
        self.btn_custom_change.setFlat(False)
        self.btn_route_del = QPushButton(Form)
        self.btn_route_del.setObjectName(u"btn_route_del")
        self.btn_route_del.setGeometry(QRect(270, 290, 250, 41))
        self.btn_route_del.setFont(font2)
        self.btn_route_del.setAutoExclusive(False)
        self.btn_route_del.setFlat(False)
        self.btn_route_add = QPushButton(Form)
        self.btn_route_add.setObjectName(u"btn_route_add")
        self.btn_route_add.setGeometry(QRect(270, 220, 250, 41))
        self.btn_route_add.setFont(font2)
        self.btn_route_add.setAutoExclusive(False)
        self.btn_route_add.setFlat(False)
        self.btn_route_change = QPushButton(Form)
        self.btn_route_change.setObjectName(u"btn_route_change")
        self.btn_route_change.setGeometry(QRect(270, 255, 250, 41))
        self.btn_route_change.setFont(font2)
        self.btn_route_change.setAutoExclusive(False)
        self.btn_route_change.setFlat(False)
        self.label_4 = QLabel(Form)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(270, 190, 250, 20))
        self.label_4.setFont(font1)
        self.label_4.setScaledContents(True)
        self.label_4.setAlignment(Qt.AlignCenter)
        self.line = QFrame(Form)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(10, 341, 511, 21))
        self.line.setFrameShape(QFrame.HLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.btn_order_add = QPushButton(Form)
        self.btn_order_add.setObjectName(u"btn_order_add")
        self.btn_order_add.setGeometry(QRect(10, 400, 374, 41))
        font3 = QFont()
        font3.setPointSize(14)
        font3.setBold(True)
        self.btn_order_add.setFont(font3)
        self.btn_order_add.setStyleSheet(u"background-color: #3FB44F")
        self.btn_order_add.setAutoExclusive(False)
        self.btn_order_add.setFlat(False)
        self.btn_order_change = QPushButton(Form)
        self.btn_order_change.setObjectName(u"btn_order_change")
        self.btn_order_change.setGeometry(QRect(10, 444, 251, 41))
        font4 = QFont()
        font4.setPointSize(14)
        font4.setBold(False)
        self.btn_order_change.setFont(font4)
        self.btn_order_change.setStyleSheet(u"")
        self.btn_order_change.setAutoExclusive(False)
        self.btn_order_change.setFlat(False)
        self.btn_order_del = QPushButton(Form)
        self.btn_order_del.setObjectName(u"btn_order_del")
        self.btn_order_del.setGeometry(QRect(270, 444, 251, 41))
        self.btn_order_del.setFont(font4)
        self.btn_order_del.setStyleSheet(u"")
        self.btn_order_del.setAutoExclusive(False)
        self.btn_order_del.setFlat(False)
        self.label_5 = QLabel(Form)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(10, 365, 511, 20))
        font5 = QFont()
        font5.setPointSize(20)
        self.label_5.setFont(font5)
        self.label_5.setScaledContents(True)
        self.label_5.setAlignment(Qt.AlignCenter)
        self.btn_order_del_2 = QPushButton(Form)
        self.btn_order_del_2.setObjectName(u"btn_order_del_2")
        self.btn_order_del_2.setGeometry(QRect(390, 395, 131, 50))
        self.btn_order_del_2.setFont(font4)
        self.btn_order_del_2.setStyleSheet(u"")
        self.btn_order_del_2.setAutoExclusive(False)
        self.btn_order_del_2.setFlat(False)

        self.retranslateUi(Form)

        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"Form", None))
        self.label.setText(QCoreApplication.translate("Form", u"\u0412\u043e\u0437\u0434\u0443\u0448\u043d\u043e\u0435 \u0441\u0443\u0434\u043d\u043e", None))
        self.btn_airplane_add.setText(QCoreApplication.translate("Form", u"\u0414\u043e\u0431\u0430\u0432\u0438\u0442\u044c", None))
        self.btn_airplane_change.setText(QCoreApplication.translate("Form", u"\u0418\u0437\u043c\u0435\u043d\u0438\u0442\u044c", None))
        self.btn_airplane_del.setText(QCoreApplication.translate("Form", u"\u0423\u0434\u0430\u043b\u0438\u0442\u044c", None))
        self.label_2.setText(QCoreApplication.translate("Form", u"\u0413\u0440\u0443\u0437", None))
        self.btn_cargo_add.setText(QCoreApplication.translate("Form", u"\u0414\u043e\u0431\u0430\u0432\u0438\u0442\u044c", None))
        self.btn_cargo_del.setText(QCoreApplication.translate("Form", u"\u0423\u0434\u0430\u043b\u0438\u0442\u044c", None))
        self.btn_cargo_change.setText(QCoreApplication.translate("Form", u"\u0418\u0437\u043c\u0435\u043d\u0438\u0442\u044c", None))
        self.btn_custom_del.setText(QCoreApplication.translate("Form", u"\u0423\u0434\u0430\u043b\u0438\u0442\u044c", None))
        self.label_3.setText(QCoreApplication.translate("Form", u"\u0417\u0430\u043a\u0430\u0437\u0447\u0438\u043a", None))
        self.btn_custom_add.setText(QCoreApplication.translate("Form", u"\u0414\u043e\u0431\u0430\u0432\u0438\u0442\u044c", None))
        self.btn_custom_change.setText(QCoreApplication.translate("Form", u"\u0418\u0437\u043c\u0435\u043d\u0438\u0442\u044c", None))
        self.btn_route_del.setText(QCoreApplication.translate("Form", u"\u0423\u0434\u0430\u043b\u0438\u0442\u044c", None))
        self.btn_route_add.setText(QCoreApplication.translate("Form", u"\u0414\u043e\u0431\u0430\u0432\u0438\u0442\u044c", None))
        self.btn_route_change.setText(QCoreApplication.translate("Form", u"\u0418\u0437\u043c\u0435\u043d\u0438\u0442\u044c", None))
        self.label_4.setText(QCoreApplication.translate("Form", u"\u041c\u0430\u0440\u0448\u0440\u0443\u0442", None))
        self.btn_order_add.setText(QCoreApplication.translate("Form", u"\u0421\u043e\u0437\u0434\u0430\u0442\u044c", None))
        self.btn_order_change.setText(QCoreApplication.translate("Form", u"\u0420\u0435\u0434\u0430\u043a\u0442\u0438\u0440\u043e\u0432\u0430\u0442\u044c", None))
        self.btn_order_del.setText(QCoreApplication.translate("Form", u"\u0423\u0434\u0430\u043b\u0438\u0442\u044c", None))
        self.label_5.setText(QCoreApplication.translate("Form", u"\u0417\u0430\u043a\u0430\u0437", None))
        self.btn_order_del_2.setText(QCoreApplication.translate("Form", u"\u0421\u043f\u0438\u0441\u043e\u043a", None))
    # retranslateUi

